defmodule Matroid.ProjectiveSetFixtures do
  # same as uniform_set_system_2_3
  def projective_set_system_1_2 do
    quote do
      @ground_set_p12 MapSet.new([1, 2, 3])
      @bases_p12 MapSet.new([
        MapSet.new([1, 2]),
        MapSet.new([1, 3]),
        MapSet.new([2, 3])
      ])
      @independent_sets_p12 MapSet.new([
        MapSet.new([]),
        MapSet.new([1]),
        MapSet.new([2]),
        MapSet.new([3]),
        MapSet.new([1, 2]),
        MapSet.new([1, 3]),
        MapSet.new([2, 3])
      ])
      @dependent_sets_p12 MapSet.new([
        MapSet.new([1, 2, 3])
      ])
      @spanning_sets_p12 MapSet.new([
        MapSet.new([1, 2]),
        MapSet.new([1, 3]),
        MapSet.new([2, 3]),
        MapSet.new([1, 2, 3])
      ])
      @non_spanning_sets_p12 MapSet.new([
        MapSet.new([]),
        MapSet.new([1]),
        MapSet.new([2]),
        MapSet.new([3])
      ])
      @circuits_p12 MapSet.new([
        MapSet.new([1, 2, 3])
      ])
      @hyperplanes_p12 MapSet.new([
        MapSet.new([1]),
        MapSet.new([2]),
        MapSet.new([3])
      ])
    end
  end

  # the Fano plane
  def projective_set_system_2_2 do
    quote do
      @ground_set_p22 MapSet.new([1, 2, 3, 4, 5, 6, 7])
      @bases_p22 MapSet.new([
        MapSet.new([1, 2, 3]),
        MapSet.new([1, 2, 4]),
        MapSet.new([1, 2, 6]),
        MapSet.new([1, 2, 7]),
        MapSet.new([1, 3, 4]),
        MapSet.new([1, 3, 5]),
        MapSet.new([1, 3, 6]),
        MapSet.new([1, 4, 5]),
        MapSet.new([1, 4, 7]),
        MapSet.new([1, 5, 6]),
        MapSet.new([1, 5, 7]),
        MapSet.new([1, 6, 7]),
        MapSet.new([2, 3, 4]),
        MapSet.new([2, 3, 5]),
        MapSet.new([2, 3, 7]),
        MapSet.new([2, 4, 5]),
        MapSet.new([2, 4, 6]),
        MapSet.new([2, 5, 6]),
        MapSet.new([2, 5, 7]),
        MapSet.new([2, 6, 7]),
        MapSet.new([3, 4, 6]),
        MapSet.new([3, 4, 7]),
        MapSet.new([3, 5, 6]),
        MapSet.new([3, 5, 7]),
        MapSet.new([3, 6, 7]),
        MapSet.new([4, 5, 6]),
        MapSet.new([4, 5, 7]),
        MapSet.new([4, 6, 7])
      ])
      @independent_sets_p22 MapSet.new([
        MapSet.new([]),
        MapSet.new([1]),
        MapSet.new([2]),
        MapSet.new([3]),
        MapSet.new([4]),
        MapSet.new([5]),
        MapSet.new([6]),
        MapSet.new([7]),
        MapSet.new([1, 2]),
        MapSet.new([1, 3]),
        MapSet.new([1, 4]),
        MapSet.new([1, 5]),
        MapSet.new([1, 6]),
        MapSet.new([1, 7]),
        MapSet.new([2, 3]),
        MapSet.new([2, 4]),
        MapSet.new([2, 5]),
        MapSet.new([2, 6]),
        MapSet.new([2, 7]),
        MapSet.new([3, 4]),
        MapSet.new([3, 5]),
        MapSet.new([3, 6]),
        MapSet.new([3, 7]),
        MapSet.new([4, 5]),
        MapSet.new([4, 6]),
        MapSet.new([4, 7]),
        MapSet.new([5, 6]),
        MapSet.new([5, 7]),
        MapSet.new([6, 7]),
        MapSet.new([1, 2, 3]),
        MapSet.new([1, 2, 4]),
        MapSet.new([1, 2, 6]),
        MapSet.new([1, 2, 7]),
        MapSet.new([1, 3, 4]),
        MapSet.new([1, 3, 5]),
        MapSet.new([1, 3, 6]),
        MapSet.new([1, 4, 5]),
        MapSet.new([1, 4, 7]),
        MapSet.new([1, 5, 6]),
        MapSet.new([1, 5, 7]),
        MapSet.new([1, 6, 7]),
        MapSet.new([2, 3, 4]),
        MapSet.new([2, 3, 5]),
        MapSet.new([2, 3, 7]),
        MapSet.new([2, 4, 5]),
        MapSet.new([2, 4, 6]),
        MapSet.new([2, 5, 6]),
        MapSet.new([2, 5, 7]),
        MapSet.new([2, 6, 7]),
        MapSet.new([3, 4, 6]),
        MapSet.new([3, 4, 7]),
        MapSet.new([3, 5, 6]),
        MapSet.new([3, 5, 7]),
        MapSet.new([3, 6, 7]),
        MapSet.new([4, 5, 6]),
        MapSet.new([4, 5, 7]),
        MapSet.new([4, 6, 7])
      ])
      @dependent_sets_p22 MapSet.new([
        MapSet.new([1, 2, 5]),
        MapSet.new([1, 3, 7]),
        MapSet.new([1, 4, 6]),
        MapSet.new([2, 3, 6]),
        MapSet.new([2, 4, 7]),
        MapSet.new([3, 4, 5]),
        MapSet.new([5, 6, 7]),
        MapSet.new([1, 2, 3, 4]),
        MapSet.new([1, 2, 3, 5]),
        MapSet.new([1, 2, 3, 6]),
        MapSet.new([1, 2, 3, 7]),
        MapSet.new([1, 2, 4, 5]),
        MapSet.new([1, 2, 4, 6]),
        MapSet.new([1, 2, 4, 7]),
        MapSet.new([1, 2, 5, 6]),
        MapSet.new([1, 2, 5, 7]),
        MapSet.new([1, 2, 6, 7]),
        MapSet.new([1, 3, 4, 5]),
        MapSet.new([1, 3, 4, 6]),
        MapSet.new([1, 3, 4, 7]),
        MapSet.new([1, 3, 5, 6]),
        MapSet.new([1, 3, 5, 7]),
        MapSet.new([1, 3, 6, 7]),
        MapSet.new([1, 4, 5, 6]),
        MapSet.new([1, 4, 5, 7]),
        MapSet.new([1, 4, 6, 7]),
        MapSet.new([1, 5, 6, 7]),
        MapSet.new([2, 3, 4, 5]),
        MapSet.new([2, 3, 4, 6]),
        MapSet.new([2, 3, 4, 7]),
        MapSet.new([2, 3, 5, 6]),
        MapSet.new([2, 3, 5, 7]),
        MapSet.new([2, 3, 6, 7]),
        MapSet.new([2, 4, 5, 6]),
        MapSet.new([2, 4, 5, 7]),
        MapSet.new([2, 4, 6, 7]),
        MapSet.new([2, 5, 6, 7]),
        MapSet.new([3, 4, 5, 6]),
        MapSet.new([3, 4, 5, 7]),
        MapSet.new([3, 4, 6, 7]),
        MapSet.new([3, 5, 6, 7]),
        MapSet.new([4, 5, 6, 7]),
        MapSet.new([1, 2, 3, 4, 5]),
        MapSet.new([1, 2, 3, 4, 6]),
        MapSet.new([1, 2, 3, 4, 7]),
        MapSet.new([1, 2, 3, 5, 6]),
        MapSet.new([1, 2, 3, 5, 7]),
        MapSet.new([1, 2, 3, 6, 7]),
        MapSet.new([1, 2, 4, 5, 6]),
        MapSet.new([1, 2, 4, 5, 7]),
        MapSet.new([1, 2, 4, 6, 7]),
        MapSet.new([1, 2, 5, 6, 7]),
        MapSet.new([1, 3, 4, 5, 6]),
        MapSet.new([1, 3, 4, 5, 7]),
        MapSet.new([1, 3, 4, 6, 7]),
        MapSet.new([1, 3, 5, 6, 7]),
        MapSet.new([1, 4, 5, 6, 7]),
        MapSet.new([2, 3, 4, 5, 6]),
        MapSet.new([2, 3, 4, 5, 7]),
        MapSet.new([2, 3, 4, 6, 7]),
        MapSet.new([2, 3, 5, 6, 7]),
        MapSet.new([2, 4, 5, 6, 7]),
        MapSet.new([3, 4, 5, 6, 7]),
        MapSet.new([1, 2, 3, 4, 5, 6]),
        MapSet.new([1, 2, 3, 4, 5, 7]),
        MapSet.new([1, 2, 3, 4, 6, 7]),
        MapSet.new([1, 2, 3, 5, 6, 7]),
        MapSet.new([1, 2, 4, 5, 6, 7]),
        MapSet.new([1, 3, 4, 5, 6, 7]),
        MapSet.new([2, 3, 4, 5, 6, 7]),
        MapSet.new([1, 2, 3, 4, 5, 6, 7])
      ])
      @spanning_sets_p22 MapSet.new([
        MapSet.new([1, 2, 3]),
        MapSet.new([1, 2, 4]),
        MapSet.new([1, 2, 6]),
        MapSet.new([1, 2, 7]),
        MapSet.new([1, 3, 4]),
        MapSet.new([1, 3, 5]),
        MapSet.new([1, 3, 6]),
        MapSet.new([1, 4, 5]),
        MapSet.new([1, 4, 7]),
        MapSet.new([1, 5, 6]),
        MapSet.new([1, 5, 7]),
        MapSet.new([1, 6, 7]),
        MapSet.new([2, 3, 4]),
        MapSet.new([2, 3, 5]),
        MapSet.new([2, 3, 7]),
        MapSet.new([2, 4, 5]),
        MapSet.new([2, 4, 6]),
        MapSet.new([2, 5, 6]),
        MapSet.new([2, 5, 7]),
        MapSet.new([2, 6, 7]),
        MapSet.new([3, 4, 6]),
        MapSet.new([3, 4, 7]),
        MapSet.new([3, 5, 6]),
        MapSet.new([3, 5, 7]),
        MapSet.new([3, 6, 7]),
        MapSet.new([4, 5, 6]),
        MapSet.new([4, 5, 7]),
        MapSet.new([4, 6, 7]),
        MapSet.new([1, 2, 5]),
        MapSet.new([1, 3, 7]),
        MapSet.new([1, 4, 6]),
        MapSet.new([2, 3, 6]),
        MapSet.new([2, 4, 7]),
        MapSet.new([3, 4, 5]),
        MapSet.new([5, 6, 7]),
        MapSet.new([1, 2, 3, 4]),
        MapSet.new([1, 2, 3, 5]),
        MapSet.new([1, 2, 3, 6]),
        MapSet.new([1, 2, 3, 7]),
        MapSet.new([1, 2, 4, 5]),
        MapSet.new([1, 2, 4, 6]),
        MapSet.new([1, 2, 4, 7]),
        MapSet.new([1, 2, 5, 6]),
        MapSet.new([1, 2, 5, 7]),
        MapSet.new([1, 2, 6, 7]),
        MapSet.new([1, 3, 4, 5]),
        MapSet.new([1, 3, 4, 6]),
        MapSet.new([1, 3, 4, 7]),
        MapSet.new([1, 3, 5, 6]),
        MapSet.new([1, 3, 5, 7]),
        MapSet.new([1, 3, 6, 7]),
        MapSet.new([1, 4, 5, 6]),
        MapSet.new([1, 4, 5, 7]),
        MapSet.new([1, 4, 6, 7]),
        MapSet.new([1, 5, 6, 7]),
        MapSet.new([2, 3, 4, 5]),
        MapSet.new([2, 3, 4, 6]),
        MapSet.new([2, 3, 4, 7]),
        MapSet.new([2, 3, 5, 6]),
        MapSet.new([2, 3, 5, 7]),
        MapSet.new([2, 3, 6, 7]),
        MapSet.new([2, 4, 5, 6]),
        MapSet.new([2, 4, 5, 7]),
        MapSet.new([2, 4, 6, 7]),
        MapSet.new([2, 5, 6, 7]),
        MapSet.new([3, 4, 5, 6]),
        MapSet.new([3, 4, 5, 7]),
        MapSet.new([3, 4, 6, 7]),
        MapSet.new([3, 5, 6, 7]),
        MapSet.new([4, 5, 6, 7]),
        MapSet.new([1, 2, 3, 4, 5]),
        MapSet.new([1, 2, 3, 4, 6]),
        MapSet.new([1, 2, 3, 4, 7]),
        MapSet.new([1, 2, 3, 5, 6]),
        MapSet.new([1, 2, 3, 5, 7]),
        MapSet.new([1, 2, 3, 6, 7]),
        MapSet.new([1, 2, 4, 5, 6]),
        MapSet.new([1, 2, 4, 5, 7]),
        MapSet.new([1, 2, 4, 6, 7]),
        MapSet.new([1, 2, 5, 6, 7]),
        MapSet.new([1, 3, 4, 5, 6]),
        MapSet.new([1, 3, 4, 5, 7]),
        MapSet.new([1, 3, 4, 6, 7]),
        MapSet.new([1, 3, 5, 6, 7]),
        MapSet.new([1, 4, 5, 6, 7]),
        MapSet.new([2, 3, 4, 5, 6]),
        MapSet.new([2, 3, 4, 5, 7]),
        MapSet.new([2, 3, 4, 6, 7]),
        MapSet.new([2, 3, 5, 6, 7]),
        MapSet.new([2, 4, 5, 6, 7]),
        MapSet.new([3, 4, 5, 6, 7]),
        MapSet.new([1, 2, 3, 4, 5, 6]),
        MapSet.new([1, 2, 3, 4, 5, 7]),
        MapSet.new([1, 2, 3, 4, 6, 7]),
        MapSet.new([1, 2, 3, 5, 6, 7]),
        MapSet.new([1, 2, 4, 5, 6, 7]),
        MapSet.new([1, 3, 4, 5, 6, 7]),
        MapSet.new([2, 3, 4, 5, 6, 7]),
        MapSet.new([1, 2, 3, 4, 5, 6, 7])
      ])
      @non_spanning_sets_p22 MapSet.new([
        MapSet.new([]),
        MapSet.new([1]),
        MapSet.new([2]),
        MapSet.new([3]),
        MapSet.new([4]),
        MapSet.new([5]),
        MapSet.new([6]),
        MapSet.new([7]),
        MapSet.new([1, 2]),
        MapSet.new([1, 3]),
        MapSet.new([1, 4]),
        MapSet.new([1, 5]),
        MapSet.new([1, 6]),
        MapSet.new([1, 7]),
        MapSet.new([2, 3]),
        MapSet.new([2, 4]),
        MapSet.new([2, 5]),
        MapSet.new([2, 6]),
        MapSet.new([2, 7]),
        MapSet.new([3, 4]),
        MapSet.new([3, 5]),
        MapSet.new([3, 6]),
        MapSet.new([3, 7]),
        MapSet.new([4, 5]),
        MapSet.new([4, 6]),
        MapSet.new([4, 7]),
        MapSet.new([5, 6]),
        MapSet.new([5, 7]),
        MapSet.new([6, 7])
      ])
      @circuits_p22 MapSet.new([
        MapSet.new([1, 2, 5]),
        MapSet.new([1, 3, 7]),
        MapSet.new([1, 4, 6]),
        MapSet.new([2, 3, 6]),
        MapSet.new([2, 4, 7]),
        MapSet.new([3, 4, 5]),
        MapSet.new([5, 6, 7]),
        MapSet.new([1, 2, 3, 4]),
        MapSet.new([1, 2, 6, 7]),
        MapSet.new([1, 3, 5, 6]),
        MapSet.new([1, 4, 5, 7]),
        MapSet.new([2, 3, 5, 7]),
        MapSet.new([2, 4, 5, 6]),
        MapSet.new([3, 4, 6, 7])
      ])
      @hyperplanes_p22 MapSet.new([
        MapSet.new([1, 2, 5]),
        MapSet.new([1, 3, 7]),
        MapSet.new([1, 4, 6]),
        MapSet.new([2, 3, 6]),
        MapSet.new([2, 4, 7]),
        MapSet.new([3, 4, 5]),
        MapSet.new([5, 6, 7])
      ])
    end
  end

  defmacro __using__(fixtures) when is_list(fixtures) do
    for fixture <- fixtures, is_atom(fixture) do
       apply(__MODULE__, fixture, [])
    end
  end
end
